app/models/soporte.py
from .db import get_connection
from werkzeug.security import generate_password_hash, check_password_hash
mydb = get_connection()

class Soporte:

    def __init__(self, email_sop, tel_sop, queja_sop, id=None) :
          self.email_sop = email_sop
          self.tel_sop = tel_sop
          self.queja_sop = queja_sop
          self.id= id

    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT email_sop, tel_sop, queja_sop FROM celulares WHERE id_sop = { id }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            soporte = Soporte(result["email_sop"], result["tel_sop"], result["queja_sop"], id)
            return soporte
        
    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
               
                sql = "INSERT INTO soporte(email_sop, tel_sop, queja_sop) VALUES(%s, %s, %s)"
                val = (self.email_sop, self.tel_sop, self.queja_sop)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        else:
            with mydb.cursor() as cursor:
                sql = 'UPDATE soporte SET email_sop = %s, tel_sop = %s, queja_sop = %s'
                sql += 'WHERE id_sop = %s'
                val = (self.email_sop, self.tel_sop, self.queja_sop, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    @staticmethod
    def get_all(limit=15, page=1):
        offset = limit * page - limit
        quejas = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT *  FROM soporte LIMIT { limit } OFFSET { offset }"
            cursor.execute(sql)
            result = cursor.fetchall()
            for sop in result:
                quejas.append(Soporte(email_sop=sop["email_sop"],
                                  tel_sop=sop["tel_sop"],
                                  queja_sop=sop["queja_sop"],
                                  id=sop["id_sop"]
                                  ) )
            return quejas
        
    @staticmethod
    def eliminar_queja(id):
        with mydb.cursor() as cursor:
            sql = "DELETE FROM soporte WHERE id_sop = %s"
            cursor.execute(sql, (id,))
            mydb.commit()

app/forms/soporte_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class CreateQuejaForm(FlaskForm):
    email = StringField('email', validators=[DataRequired()])
    telefono = StringField('telefono', validators=[DataRequired()])
    queja = TextAreaField('queja', validators=[DataRequired()])
    submit = SubmitField('Guardar')

app/views/celulares_views.py
from flask import Blueprint, render_template, redirect, url_for, abort
from models.celulares import Celular
import traceback

from forms.celulares_form import CreateCelularForm, UpdateCelularForm

from utils.file_handler import save_image

celulares_views = Blueprint('celulares',__name__)

@celulares_views.route("/celulares/<int:page>")
def celulares(page=1):
    limit = 8

    cels = Celular.get_all(limit=limit, page=page)
    total_cels = Celular.count()
    pages = ((total_cels // limit)+ 1)
    return render_template('/celulares/celulares.html', pages=pages, cels=cels)

@celulares_views.route("/celulares_cli/<int:page>")
def celulares_cli(page=1):
    limit = 8

    cels = Celular.get_all(limit=limit, page=page)
    total_cels = Celular.count()
    pages = ((total_cels // limit)+ 1)  
    
    return render_template('/celulares/celulares_cli.html', cels=cels, pages=pages)

@celulares_views.route("/admin/celulares_list/")
def celulares_list(page=1):
    limit =8
    cels = Celular.get_all(limit=limit, page=page)
    total_cels = Celular.count()
    pages = ((total_cels // limit)+ 1)
    return render_template('/celulares/celulares_list.html', pages=pages, cels=cels)


@celulares_views.route('/celulares/<int:id>/celular/')
def celular(id):
    celular = Celular.get(id)
    if celular is None: abort(404)
    return render_template('celulares/celular.html', celular=celular)

@celulares_views.route('/celulares/<int:id>/celular_cli/')
def celular_cli(id):
    celular = Celular.get(id)
    if celular is None: abort(404)
    return render_template('celulares/celular_cli.html', celular=celular)



@celulares_views.route("/celulares/insertarcelular/", methods=['GET', 'POST'])
def insert_celular():
    form = CreateCelularForm()

    if form.validate_on_submit():
        marca = form.marca.data
        modelo = form.modelo.data
        color = form.color.data 
        stock = form.stock.data
        almacenamiento = form.almacenamiento.data
        condicion = form.condicion.data
        idProveedor = form.idProveedor.data
        precio = form.precio.data
        f = form.image.data
        image = ""
        if f:
            image = save_image(f, 'images/Celulares')
        celular = Celular(marca=marca,
                            modelo=modelo,
                            color=color,
                            stock=stock,
                            almacenamiento=almacenamiento,
                            condicion=condicion,
                            idProveedor=idProveedor,
                            precio=precio,
                            image=image)
        celular.save()
      

        return redirect(url_for('celulares.celulares_list'))

    return render_template('celulares/insertar_cel.html', form=form)

@celulares_views.route('/celulares/<int:id>/updatecel', methods=('GET', 'POST'))
def updatecel(id):
    form = UpdateCelularForm()
    cel = Celular.get(id)
    if cel is None:
        abort(404)
    if form.validate_on_submit():
        cel.modelo=form.marca.data
        cel.color=form.modelo.data
        cel.stock=form.stock.data
        cel.almacenamiento=form.almacenamiento.data
        cel.condicion=form.condicion.data
        cel.idProveedor=form.idProveedor.data
        cel.precio=form.precio.data
        f = form.image.data
        if f:
            image = save_image(f, 'images/Celulares')
            cel.image = image
        cel.save()
        return redirect(url_for('celulares.celulares_list'))
    form.marca.data = cel.marca
    form.modelo.data = cel.modelo
    form.color.data = cel.color
    form.stock.data = cel.stock
    form.almacenamiento.data = cel.almacenamiento
    form.condicion.data = cel.condicion
    form.idProveedor.data = cel.idProveedor
    form.precio.data = cel.precio
    image = cel.image
    return render_template('celulares/insertar_cel.html', form=form, image=image)

@celulares_views.route('/celulares/<int:id>/deletecel/', methods=['POST'])
def deletecel(id):
    Celular.delete_celular(id)

    return redirect(url_for('celulares.celulares_list'))

app/views/soporte_views.py
from flask import Blueprint, render_template, redirect, url_for, abort
soporte_views = Blueprint('soporte',__name__)

from models.soporte import Soporte, mydb

from forms.soporte_form import CreateQuejaForm


@soporte_views.route("/soporte/", methods = ('GET','POST'))
def soporte():
    form = CreateQuejaForm()

    if form.validate_on_submit():
      email = form.email.data
      telefono = form.telefono.data
      queja = form.queja.data
      sop = Soporte(email, telefono, queja)
      sop.save()
      return redirect(url_for('soporte.soporte'))
    return render_template('soporte/soporte.html', form=form)

@soporte_views.route("/liistsoporte/")
def soporte_list():
  quejas = []  
  with mydb.cursor(dictionary=True) as cursor:
        sql = f"SELECT * FROM soporte "
        cursor.execute(sql)
        result = cursor.fetchall()

        for queja in result:
            queja_obj=Soporte(email_sop=queja["email_sop"],
                    tel_sop=queja["tel_sop"],
                    queja_sop=queja["queja_sop"],
                    id=queja["id_sop"]
            )
            quejas.append(queja_obj)
  return render_template('soporte/soporte_list.html', quejas=quejas)

@soporte_views.route('/soporte/admin/eliminar/<int:id>')
def eliminar_queja(id):
    Soporte.eliminar_queja(id)
    return redirect(url_for('soporte.soporte_list'))

app/templates/soporte/soporte.html
{% extends 'index_cliente.html' %} 
 
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/produtcos.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='css/articulo.css') }}">
{% endblock %}

{% block  body %}
  <form  method="post">
      
      {{ form.csrf_token }}
        
        <div>
          {{ form.email.label }}
          {{ form.email() }}
          {% if form.email.errors %}
          {% for error in form.email.errors %}
          <p>{{ error }}</p>
          {% endfor %}
          {% endif %}
        </div>
        
        <div>
          {{ form.telefono.label }}
          {{ form.telefono() }}
          {% if form.telefono.errors %}
          {% for error in form.telefono.errors %}
          <p>{{ error }}</p>
          {% endfor %}
          {% endif %}
                
        </div>
        <div>
          {{ form.queja.label }}
          {{ form.queja() }}
          {% if form.queja.errors %}
          {% for error in form.queja.errors %}
          <p>{{ error }}</p>
          {% endfor %}
          {% endif %}
          
        </div>
        <div>
          {{ form.submit(class="btn") }}
        </div>
        
  </form>   

{% endblock %}

app/templates/soporte/soporte_list.html
{% extends 'index_admin.html' %} 
 
{% block title %}
    Celulares
{% endblock %}



{% block  body %}
<div id="titulo"><h1 id="titulo_art">LISTA DE CELULARES</h1></div> 
<div class="head">
    <a href="{{ url_for('celulares.insert_celular') }}" class="btn">Agregar celular</a>
</div>

<table id="categories">
    <thead>
        <tr>
            <th>ID</th>
            <th>Email del Cliente</th>
            <th>Telefono de Cliente</th>
            <th>Queja</th>
            

        </tr>
    </thead>
    <tbody>
        {% for queja in quejas %}
            <tr>
                
                <td>{{ queja.id }}</td>
                <td>{{ queja.email_sop }}</td>
                <td>{{ queja.tel_sop }}</td>
                <td>{{ queja.queja_sop }}</td>
                <td><button class="btn_delete"><a href="{{ url_for('soporte.eliminar_queja', id=queja.id) }}">Eliminar</a></button></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}