app/models/accesorios.py
from .db import get_connection

mydb = get_connection()

class Accesorio:

    def __init__(self, categoria, color,
                 tipo, stock=1 ,especificacionExtra="", precio=0.0,image="",id=None):
        self.categoria = categoria
        self.color = color
        self.tipo = tipo
        self.stock = stock
        self.especificacionExtra = especificacionExtra
        self.precio = precio
        self.image = image
        self.id = id


    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
               
                sql = "INSERT INTO accesorios(categoria, color, tipo, stock, especificacionExtra, precio, image) VALUES(%s, %s, %s, %s, %s, %s, %s)"
                val = (self.categoria, self.color, self.tipo, self.stock, self.especificacionExtra, self.precio, self.image)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        else:
            with mydb.cursor() as cursor:
                sql = 'UPDATE accesorios SET categoria = %s, color = %s, tipo =%s, stock = %s, especificacionExtra = %s, precio = %s, image = %s'
                sql += 'WHERE idAcc = %s'
                val = (self.categoria, self.color, self.tipo, self.stock, self.especificacionExtra, self.precio, self.image, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM accesorios WHERE idAcc = { id }"
            cursor.execute(sql)
            acc = cursor.fetchone()
            if acc:
               acc = Accesorio(categoria=acc["categoria"],
                                  color=acc["color"],
                                  tipo=acc["tipo"],
                                  stock=acc["stock"],
                                  especificacionExtra=acc["especificacionExtra"],
                                  precio=acc["precio"],
                                  image=acc["image"],
                                  id=acc["idAcc"])
            return acc 
        

    @staticmethod
    def get_all_art(limit=4, page=1):
        offset = limit * page - limit
        accesorios = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT *  FROM accesorios LIMIT { limit } OFFSET { offset }"
            cursor.execute(sql)
            result = cursor.fetchall()
            for accesorio in result:
                accesorios.append(Accesorio(categoria=accesorio["categoria"],
                                  color=accesorio["color"],
                                  tipo=accesorio["tipo"],
                                  stock=accesorio["stock"],
                                  especificacionExtra=accesorio["especificacionExtra"],
                                  precio=accesorio["precio"],
                                  image=accesorio["image"],
                                  id=accesorio["idAcc"]))
            return accesorios
        
    @staticmethod
    def get_all(limit=8, page=1):
        offset = limit * page - limit
        accesorios = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT *  FROM accesorios LIMIT { limit } OFFSET { offset }"
            cursor.execute(sql)
            result = cursor.fetchall()
            for accesorio in result:
                accesorios.append(Accesorio(categoria=accesorio["categoria"],
                                  color=accesorio["color"],
                                  tipo=accesorio["tipo"],
                                  stock=accesorio["stock"],
                                  especificacionExtra=accesorio["especificacionExtra"],
                                  precio=accesorio["precio"],
                                  image=accesorio["image"],
                                  id=accesorio["idAcc"]))
            return accesorios
        
           
    @staticmethod
    def get_by_any(precio):
        accesorios = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT *FROM accesorios WHERE precio LIKE { precio }"
            cursor.execute(sql)
            result = cursor.fetchall()
            for accesorio in result:
                accesorios.append(Accesorio(categoria=accesorio["categoria"],
                                  color=accesorio["color"],
                                  tipo=accesorio["tipo"],
                                  stock=accesorio["stock"],
                                  especificacionExtra=accesorio["especificacionExtra"],
                                  precio=accesorio["precio"],
                                  image=accesorio["image"],
                                  id=accesorio["idAcc"]))
            return accesorios
        
    
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM accesorios WHERE idAcc = { self.id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id
        
    @staticmethod
    def count():
        with mydb.cursor(dictionary=True) as cursor:
            sql = "SELECT count(idAcc) as total FROM accesorios"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result['total']

        

    

        

app/forms/accesorios_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField, IntegerField,TextAreaField, SelectField
from wtforms.validators import DataRequired, NumberRange
from flask_wtf.file import FileField, FileAllowed

from models.accesorios import Accesorio
class CreateAccesorioForm(FlaskForm):

    accs=[]
    
    categoria = StringField('categoria', validators=[DataRequired()])
    tipo = StringField('tipo', validators=[DataRequired()])
    stock = IntegerField('stock', validators=[DataRequired(), NumberRange(min=0, max=None)])
    color = StringField('color', validators=[DataRequired()])
    especificacionExtra = TextAreaField('especificacionExtra', validators=[DataRequired()])
    precio = FloatField('precio', validators=[DataRequired(), NumberRange(min=0.0, max=None)])
  
    image = FileField('Imagen de Producto', 
                      validators=[FileAllowed(['jpg', 'png', 'jpeg'], 'Solo imagenes!')])
    submit = SubmitField('Guardar')

class FiltroBusqueda(FlaskForm):
     precio = FloatField('precio', validators=[DataRequired(), NumberRange(min=0.0, max=None)])
     submit = SubmitField('Filtrar')

class UpdateAccesorioForm(FlaskForm):


    categoria = StringField('categoria', validators=[DataRequired()])
    tipo = TextAreaField('tipo', validators=[DataRequired()])
    color = StringField('color', validators=[DataRequired()])
    stock = IntegerField('stock', validators=[DataRequired(), NumberRange(min=0, max=None)])
    especificacionExtra = TextAreaField('especificacionExtra', validators=[DataRequired()])
    precio = FloatField('precio', validators=[DataRequired(), NumberRange(min=0.0, max=None)])
   
    image = FileField('Imagen de Producto', 
                      validators=[FileAllowed(['jpg', 'png', 'jpeg'], 'Solo imagenes!')])
    submit = SubmitField('Actualizar')

app/forms/audio_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField, IntegerField,TextAreaField, SelectField
from wtforms.validators import DataRequired, NumberRange
from flask_wtf.file import FileField, FileAllowed

from models.audio import Audio

class CreateAudioForm(FlaskForm):

    auds=[]
    
    marca = StringField('marca', validators=[DataRequired()])
    modelo = StringField('modelo', validators=[DataRequired()])
    conexion = StringField('conexion', validators=[DataRequired()])
    tipo = StringField('tipo', validators=[DataRequired()])
    stock = IntegerField('stock', validators=[DataRequired(), NumberRange(min=0, max=None)])
    precio = FloatField('precio', validators=[DataRequired(), NumberRange(min=0.0, max=None)])
  
    image = FileField('Imagen de Producto', 
                      validators=[FileAllowed(['jpg', 'png', 'jpeg'], 'Solo imagenes!')])
    submit = SubmitField('Guardar')

class UpdateAudioForm(FlaskForm):


    marca = StringField('marca', validators=[DataRequired()])
    modelo = StringField('modelo', validators=[DataRequired()])
    conexion = StringField('conexion', validators=[DataRequired()])
    tipo = StringField('tipo', validators=[DataRequired()])
    stock = IntegerField('stock', validators=[DataRequired(), NumberRange(min=0, max=None)])
    precio = FloatField('precio', validators=[DataRequired(), NumberRange(min=0.0, max=None)])
  
    image = FileField('Imagen de Producto', 
                      validators=[FileAllowed(['jpg', 'png', 'jpeg'], 'Solo imagenes!')])
    submit = SubmitField('Guardar')

app/views/articulos_views.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash
import traceback

articulos_views = Blueprint('articulos',__name__)

from models.accesorios import Accesorio
from models.audio import Audio
from forms.accesorios_form import CreateAccesorioForm, FiltroBusqueda, UpdateAccesorioForm
from forms.audio_form import CreateAudioForm, UpdateAudioForm

from utils.file_handler import save_image
@articulos_views.route("/articulos")
def articulos():
    accs = Accesorio.get_all_art()
    
    auds = Audio.get_all()
    return render_template('articulos/articulos.html',accs=accs, auds = auds)

@articulos_views.route("/articulos/cli")
def articulos_cli():
    accs = Accesorio.get_all_art()
    
    auds = Audio.get_all()
    return render_template('articulos/articulos_cli.html',accs=accs, auds = auds)

@articulos_views.route("/accesorios/<int:page>")
def accesorios(page=1):
    limit = 8

    accs = Accesorio.get_all(limit=limit, page=page)
    total_acc = Accesorio.count()
    pages = ((total_acc // limit)+ 1)
   
    
    return render_template('articulos/accesorios.html',accs=accs, pages=pages)

@articulos_views.route("/accesorios/cli/<int:page>")
def accesorios_cli(page=1):
    limit = 8
    accs = Accesorio.get_all(limit=limit, page=page)
    total_acc = Accesorio.count()
    pages = ((total_acc // limit)+ 1)
   
    
    return render_template('articulos/accesorios_cli.html',accs=accs, pages=pages)

@articulos_views.route("/admin/listaaccesorios/<int:page>")
def accesorios_list(page=1):
    limit = 8
    accs = Accesorio.get_all(limit=limit, page=page)
    total_acc=Accesorio.count()
    pages = ((total_acc // limit)+ 1)
    return render_template('articulos/accesorios_list.html',accs=accs, pages=pages)

@articulos_views.route("/audios/<int:page>")
def audios(page=1):
    limit = 8
    auds = Audio.get_all(limit=limit, page=page)
    total_aud=Audio.count()
    pages = ((total_aud // limit)+ 1)
    return render_template('articulos/audios.html',auds=auds, pages=pages)

@articulos_views.route("/audios/cli/<int:page>")
def audios_cli(page=1):
    limit = 8
    auds = Audio.get_all(limit=limit, page=page)
    total_aud=Audio.count()
    pages = ((total_aud // limit)+ 1)
    return render_template('articulos/audios_cli.html',auds=auds, pages=pages)

@articulos_views.route("/admin/audios/<int:page>")
def audios_list(page=1):
    limit = 8
    auds = Audio.get_all(limit=limit, page=page)
    total_aud=Audio.count()
    pages = ((total_aud // limit)+ 1)
    return render_template('articulos/audios_list.html',auds=auds, pages=pages)

@articulos_views.route("/articulos/crear_accesorio",  methods=['GET', 'POST'])
def crear_accesorio():
    form = CreateAccesorioForm()
    
    if form.validate_on_submit():
        categoria = form.categoria.data
        tipo = form.tipo.data
        stock = form.stock.data
        color = form.color.data
        especificacionExtra = form.especificacionExtra.data
        precio = form.precio.data
        f = form.image.data
        image = ""
        if f:
            image = save_image(f, 'images/Accesorios')
        accesorio = Accesorio(categoria=categoria, 
                          tipo=tipo,
                          stock=stock,
                          color=color,
                          especificacionExtra=especificacionExtra,
                          precio=precio,
                          image=image)
        accesorio.save()
        flash ('Listo!')
        return redirect(url_for('articulos.accesorios_list', page=1))

    return render_template('articulos/insertar_acc.html', form=form)

@articulos_views.route("/articulos/crear_audio",  methods=['GET', 'POST'])
def crear_audio():
    form = CreateAudioForm()
    
    if form.validate_on_submit():
        marca = form.marca.data
        modelo = form.modelo.data
        conexion = form.conexion.data
        tipo = form.tipo.data
        stock = form.stock.data
        precio = form.precio.data
        f = form.image.data
        image = ""
        if f:
            image = save_image(f, 'images/Audio_img')
        audio = Audio(marca=marca, 
                          modelo=modelo,
                          conexion=conexion,
                          tipo=tipo,
                          stock=stock,
                          precio=precio,
                          image=image)
        audio.save()
        flash ('Listo!')
        return redirect(url_for('articulos.audios_list', page=1))

    return render_template('articulos/insertar_audio.html', form=form)

@articulos_views.route('/articulos/<int:id>/accesorio/')
def accesorio(id):
    accesorio = Accesorio.get(id)
    if accesorio is None: abort(404)
    return render_template('articulos/accesorio.html', accesorio=accesorio)

@articulos_views.route('/articulos/<int:id>/accesorio/cli')
def accesorio_cli(id):
    accesorio = Accesorio.get(id)
    if accesorio is None: abort(404)
    return render_template('articulos/accesorio_cli.html', accesorio=accesorio)




@articulos_views.route('/articulos/<int:id>/audio/')
def audio(id):
    audio = Audio.get(id)
    if audio is None: abort(404)
    return render_template('articulos/audio.html', audio=audio)

@articulos_views.route('/articulos/<int:id>/audio/cli')
def audio_cli(id):
    audio = Audio.get(id)
    if audio is None: abort(404)
    return render_template('articulos/audio_cli.html', audio=audio)

@articulos_views.route('/product/<int:id>/delete_acc/', methods=['POST'])
def delete_acc(id):
    accesorio = Accesorio.get(id)
    if accesorio is None: abort(404)
    accesorio.delete()
    return redirect(url_for('articulos.accesorios_list',page=1))

@articulos_views.route('/product/<int:id>/delete_aud/', methods=['POST'])
def delete_aud(id):
    audio = Audio.get(id)
    if audio is None: abort(404)
    audio.delete()
    return redirect(url_for('articulos.audios_list', page=1))

@articulos_views.route('/products/<int:id>/update_acc/', methods=('GET', 'POST'))
def update_acc(id):
    form = UpdateAccesorioForm()
    accesorio = Accesorio.get(id)
    if accesorio is None:
        abort(404)
    if form.validate_on_submit():
        accesorio.categoria = form.categoria.data
        accesorio.tipo = form.tipo.data
        accesorio.stock = form.stock.data
        accesorio.color = form.color.data
        accesorio.precio = form.precio.data
        accesorio.especificacionExtra = form.especificacionExtra.data
        f = form.image.data
        if f:
            image = save_image(f, 'images/Accesorios')
            accesorio.image = image
        accesorio.save()
        return redirect(url_for('articulos.accesorios_list', page=1))
    form.categoria.data = accesorio.categoria
    form.tipo.data = accesorio.tipo
    form.stock.data = accesorio.stock
    form.color.data = accesorio.color
    form.precio.data = accesorio.precio
    form.especificacionExtra.data = accesorio.especificacionExtra
    image = accesorio.image
    return render_template('articulos/insertar_acc.html', form=form, image=image)

@articulos_views.route('/products/<int:id>/update_audio/', methods=('GET', 'POST'))
def update_audio(id):
    form = UpdateAudioForm()
    audio = Audio.get(id)
    if audio is None:
        abort(404)
    if form.validate_on_submit():
        audio.marca = form.marca.data
        audio.modelo = form.modelo.data
        audio.tipo = form.tipo.data
        audio.conexion = form.conexion.data
        audio.stock = form.stock.data
        audio.precio = form.precio.data
   
        f = form.image.data
        if f:
            image = save_image(f, 'images/Audio_img')
            audio.image = image
        audio.save()
        return redirect(url_for('articulos.audios_list', page=1))
    form.marca.data = audio.marca
    form.modelo.data= audio.modelo
    form.tipo.data = audio.tipo
    form.conexion.data = audio.conexion
    form.stock.data = audio.stock
    form.precio.data = audio.precio
    image = audio.image
   
    
    return render_template('articulos/insertar_audio.html', form=form, image=image)

app/templates/articulos/accesorios.html
{% extends 'index.html' %} 
 
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/produtcos.css') }}">
{% endblock %}

{% block body %}
<div id="titulo"><h1 id="titulo_art">ACCESORIOS</h1></div>
           

     <section class="seccion">
         {% for acc in accs %}
        <div class="card"> 
            <a href="{{ url_for('articulos.accesorio', id=acc.id) }}" >
            <img src="{{ url_for('static', filename='images/Accesorios/' + acc.image) }}" alt="" width="300px" class="img_articulo">
             <div class="item" > {{ acc.precio }} </div>
             <div class="item" >{{ acc.id }}</div>
             <div class="item">{{ acc.categoria }}</div>
             <div class="item">{{ acc.color }}</div>
             <div class="item">{{ acc.tipo }}</div>
             <div class="item">{{ acc.stock }}</div>
             <div class="item"> {{ acc.especificacionExtra }}</div>
            </a>
            </div>
            
            {% endfor %}
     </section>
     <div class="paginador">
            {% for i in range(pages) %}
        <a href="{{ url_for('articulos.accesorios', page=(i + 1)) }}" class="paginas" >{{ i + 1 }}</a>
            {% endfor %}
            </div>
        {% endblock %}

app/templates/articulos/accesorios_list.html
{% extends 'index_admin.html' %} 
 
{% block title %}
    Accesorios
{% endblock %}

{% block body %}
<div id="titulo"><h1 id="titulo_art">LISTA DE ACCCESORIOS</h1></div> 
<div class="head">
    <a href="{{ url_for('articulos.crear_accesorio') }}" class="btn">Agregar accesorios</a>
</div>
           
<table id="categories">
    <thead>
        <tr>
            <th>Categoria</th>
            <th>Tipo</th>
            <th>Color</th>
            <th>Descripcion</th>
            <th>Stock</th>
            <th>Precio</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for acc in accs %}
            <tr>
                <td><a href="{{ url_for('articulos.accesorio', id=acc.id) }}">{{ acc.categoria }}</a></td>
                <td>{{ acc.tipo }}</td>
                <td>{{ acc.color }}</td>
                <td>{{ acc.especificacionExtra }}</td>
                <td>{{ acc.stock }}</td>
                <td>{{ acc.precio }}</td>
                <td>   
                    <a href="{{ url_for('articulos.update_acc', id=acc.id) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit" width="36" height="36" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" />
                        <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" />
                        <path d="M16 5l3 3" />
                      </svg>
                    </a>
                    <form 
                        action="{{ url_for('articulos.delete_acc', id=acc.id) }}" 
                        method="post">
                        <button type="submit" onclick="return confirm('Seguro?')">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash" width="36" height="36" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M4 7l16 0" />
                                <path d="M10 11l0 6" />
                                <path d="M14 11l0 6" />
                                <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                                <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                              </svg>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<div class="paginador">
{% for i in range(pages) %}
        <a href="{{ url_for('articulos.accesorios_list', page=(i + 1)) }}" class="paginas" >{{ i + 1 }}</a>
            {% endfor %}
</div>
{% endblock %}

app/templates/articulos/articulos.html
{% extends 'index.html' %} 
 
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/produtcos.css') }}">
{% endblock %}

{% block  body %}

 <div id="titulo"><h1 id="titulo_art">ARTICULOS</h1></div>

 <div class="seccionn">
     <section class="seccion_articulos">
         {% for acc in accs %}
        <div class="card"> 
            <a href="{{ url_for('articulos.accesorio', id=acc.id) }}" >
            <img src="{{ url_for('static', filename='images/Accesorios/' + acc.image) }}" alt="" width="300px" class="img_articulo">
             <div class="articulo" ><p>${{ acc.precio }}</p> </div>
             <div class="articulo">{{ acc.categoria }}</div>
             <div class="articulo">{{ acc.tipo }}</div>
             <div class="articulo">{{ acc.color }}</div>
             <div class="articulo">{{ acc.stock }}</div>
             <div class="articulo"> {{ acc.especificacionExtra }}</div>
        
             </a>
            </div>

            {% endfor %}
           
            <a href="{{ url_for('articulos.accesorios', page=1) }}">
                <div class="vermas">
                    <h1>VER MAS</h1>
                </div>
                </a>
          
        </section>
      
 </div>
        <section class="seccion_articulos">
            {% for aud in auds %}
            <div class="card"> 
                <a href="{{ url_for('articulos.audio', id=aud.id) }}">

                <img src="{{ url_for('static', filename='images/Audio_img/' + aud.image) }}" alt="" width="300px" class="img_articulo">
                <div class="articulo">{{ aud.id }} </div>
                <div class="articulo">{{ aud.marca }}</div>
                <div class="articulo">{{ aud.modelo }}</div>
                <div class="articulo">{{ aud.conexion }}</div>
                <div class="articulo">{{ aud.tipo }}</div>
                <div class="articulo">{{ aud.stock }}</div>
                <div class="articulo">{{ aud.precio }}</div>
                </a>
            </div>
          
            {% endfor %}
            <a href="{{ url_for('articulos.audios', page=1) }}">
                <div class="vermas">
                    <h1>VER MAS</h1>
                </div>
                </a>
           </section>
{% endblock %}

app/templates/articulos/articulos_cli.html
{% extends 'index_cliente.html' %} 
 
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/produtcos.css') }}">
{% endblock %}

{% block  body %}

 <div id="titulo"><h1 id="titulo_art">ARTICULOS</h1></div>

 <div class="seccionn">
     <section class="seccion_articulos">
         {% for acc in accs %}
        <div class="card"> 
            <a href="{{ url_for('articulos.accesorio_cli', id=acc.id) }}" >
            <img src="{{ url_for('static', filename='images/Accesorios/' + acc.image) }}" alt="" width="300px" class="img_articulo">
             <div class="articulo" ><p>${{ acc.precio }}</p> </div>
             <div class="articulo">{{ acc.categoria }}</div>
             <div class="articulo">{{ acc.tipo }}</div>
             <div class="articulo">{{ acc.color }}</div>
             <div class="articulo">{{ acc.stock }}</div>
             <div class="articulo"> {{ acc.especificacionExtra }}</div>
        
             </a>
            </div>

            {% endfor %}
            <a href="{{ url_for('articulos.accesorios_cli', page=1) }}">
                <div class="vermas">
                    <h1> VER MAS </h1>
                </div>
                </a>
        </section>
      
 </div>
        <section class="seccion_articulos">
            {% for aud in auds %}
            <div class="card"> 
                <a href="{{ url_for('articulos.audio_cli', id=aud.id) }}" >

                <img src="{{ url_for('static', filename='images/Audio_img/' + aud.image) }}" alt="" width="300px" class="img_articulo">
                <div class="articulo">{{ aud.id }} </div>
                <div class="articulo">{{ aud.marca }}</div>
                <div class="articulo">{{ aud.modelo }}</div>
                <div class="articulo">{{ aud.conexion }}</div>
                <div class="articulo">{{ aud.tipo }}</div>
                <div class="articulo">{{ aud.stock }}</div>
                <div class="articulo">{{ aud.precio }}</div>
                </a>
            </div>
          
            {% endfor %}
            <a href="{{ url_for('articulos.audios_cli', page=1) }}">
                <div class="vermas">
                    <h1> VER MAS </h1>
                </div>
                </a>
           </section>
{% endblock %}

app/templates/articulos/audios_list.html
{% extends 'index_admin.html' %}

{% block title %}
    Audio
{% endblock %}

{% block body %}
<div id="titulo"><h1 id="titulo_art">LISTA DE AUDIOS</h1></div> 
<div class="head">
    <a href="{{ url_for('articulos.crear_audio') }}" class="btn">Agregar audio</a>
</div>

<table id="categories">
    <thead>
        <tr>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Tipo</th>
            <th>Conexión</th>
            <th>Stock</th>
            <th>Precio</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for aud in auds %}
            <tr>
                <td><a href="{{ url_for('articulos.audio', id=aud.id) }}">{{ aud.marca }}</a></td>
                <td>{{ aud.modelo }}</td>
                <td>{{ aud.tipo }}</td>
                <td>{{ aud.conexion }}</td>
                <td>{{ aud.stock }}</td>
                <td>{{ aud.precio }}</td>
                <td>
                    <a href="{{ url_for('articulos.update_audio', id=aud.id) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit" width="36" height="36" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" />
                        <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" />
                        <path d="M16 5l3 3" />
                      </svg>
                    </a>
                    <form 
                        action="{{ url_for('articulos.delete_aud', id=aud.id) }}" 
                        method="post">
                        <button type="submit" onclick="return confirm('Seguro?')">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash" width="36" height="36" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M4 7l16 0" />
                                <path d="M10 11l0 6" />
                                <path d="M14 11l0 6" />
                                <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                                <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                              </svg>
                        </button>
                    </form>
                </td>
            </tr>
            
        {% endfor %}
    </tbody>
</table>
<div class="paginador">
{% for i in range(pages) %}
        <a href="{{ url_for('articulos.audios_list', page=(i + 1)) }}" class="paginas" >{{ i + 1 }}</a>
            {% endfor %}
</div>

{% endblock %}