app/models/celulares.py
from .db import get_connection

mydb = get_connection()

class Celular:

    def __init__(self, marca, modelo, color, stock, almacenamiento,condicion, idProveedor,precio,image, id=None ):
        self.marca = marca
        self.modelo = modelo
        self.color = color
        self.stock = stock
        self.almacenamiento = almacenamiento
        self.condicion = condicion
        self.idProveedor = idProveedor
        self.precio = precio
        self.image = image
        self.id = id

    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
               
                sql = "INSERT INTO celulares(marca, modelo, color, stock, almacenamiento, condicion,idProveedor,precio, image) VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s)"
                val = (self.marca, self.modelo, self.color, self.stock, self.almacenamiento, self.condicion, self.idProveedor,self.precio ,self.image)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        else:
            with mydb.cursor() as cursor:
                sql = 'UPDATE celulares SET marca = %s, modelo = %s, color =%s, stock = %s, almacenamiento = %s, condicion = %s, idProveedor= %s, precio=%s, image=%s'
                sql += 'WHERE idCel = %s'
                val = (self.marca, self.modelo, self.color, self.stock, self.almacenamiento, self.condicion, self.idProveedor,self.precio ,self.image, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
    @staticmethod        
    def delete_celular(id):
        with mydb.cursor() as cursor:
            sql = "DELETE FROM celulares WHERE idCel = %s "
            cursor.execute(sql, (id,))
            mydb.commit()

    
    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM celulares WHERE idCel = { id }"
            cursor.execute(sql)
            cel = cursor.fetchone()
            if cel:
               cel = Celular(marca=cel["marca"],
                                  modelo=cel["modelo"],
                                  color=cel["color"],
                                  stock=cel["stock"],
                                  almacenamiento=cel["almacenamiento"],
                                  condicion=cel["condicion"],
                                  idProveedor=cel["idProveedor"],
                                  precio=cel["precio"],
                                  image=cel["image"],
                                  id=cel["idCel"])
            return cel
        
    @staticmethod
    def get_all(limit=8, page=1):
        offset = limit * page - limit
        celulares = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT * FROM celulares LIMIT { limit } OFFSET { offset }"
            cursor.execute(sql)
            result = cursor.fetchall()
            for celular in result:
                celulares.append(Celular( marca=celular["marca"],
                                  modelo=celular["modelo"],
                                  color=celular["color"],
                                  stock=celular["stock"],
                                  almacenamiento=celular["almacenamiento"],
                                  condicion=celular["condicion"],
                                  idProveedor=celular["idProveedor"],
                                  precio=celular["precio"],
                                  image=celular["image"],
                                  id=celular["idCel"]))
            return celulares

    @staticmethod
    def count():
        with mydb.cursor(dictionary=True) as cursor:
            sql = "SELECT count(idCel) as total FROM celulares"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result['total']

app/forms/celulares_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, FloatField, IntegerField,TextAreaField, SelectField
from wtforms.validators import DataRequired, NumberRange
from flask_wtf.file import FileField, FileAllowed


from models.celulares import Celular

class CreateCelularForm(FlaskForm):
   
    cels=[]
    
    marca = StringField('marca', validators=[DataRequired()])
    modelo = StringField('modelo', validators=[DataRequired()])
    color = StringField('color', validators=[DataRequired()])
    stock = IntegerField('stock', validators=[DataRequired(), NumberRange(min=0, max=None)])
    almacenamiento = StringField('almacenamiento', validators=[DataRequired()])
    condicion = StringField('condicion', validators=[DataRequired()])
    idProveedor = StringField('idProveedor', validators=[DataRequired()])
    precio = FloatField('precio', validators=[DataRequired(), NumberRange(min=0.0, max=None)])
    image = FileField('Imagen de Producto', 
    validators=[FileAllowed(['jpg', 'png', 'jpeg'], 'Solo imagenes!')])
    submit = SubmitField('Guardar')

class UpdateCelularForm(FlaskForm):
    marca = StringField('marca', validators=[DataRequired()])
    modelo = StringField('modelo', validators=[DataRequired()])
    color = StringField('color', validators=[DataRequired()])
    stock = IntegerField('stock', validators=[DataRequired(), NumberRange(min=0, max=None)])
    almacenamiento = StringField('almacenamiento', validators=[DataRequired()])
    condicion = StringField('condicion', validators=[DataRequired()])
    idProveedor = StringField('idProveedor', validators=[DataRequired()])
    precio = FloatField('precio', validators=[DataRequired(), NumberRange(min=0.0, max=None)])
  
    image = FileField('Imagen de Producto', 
                      validators=[FileAllowed(['jpg', 'png', 'jpeg'], 'Solo imagenes!')])
    submit = SubmitField('Guardar')

app/views/celulares_views.py
from flask import Blueprint, render_template, redirect, url_for, abort
from models.celulares import Celular
import traceback

from forms.celulares_form import CreateCelularForm, UpdateCelularForm

from utils.file_handler import save_image

celulares_views = Blueprint('celulares',__name__)

@celulares_views.route("/celulares/<int:page>")
def celulares(page=1):
    limit = 8

    cels = Celular.get_all(limit=limit, page=page)
    total_cels = Celular.count()
    pages = ((total_cels // limit)+ 1)
    return render_template('/celulares/celulares.html', pages=pages, cels=cels)

@celulares_views.route("/celulares_cli/<int:page>")
def celulares_cli(page=1):
    limit = 8

    cels = Celular.get_all(limit=limit, page=page)
    total_cels = Celular.count()
    pages = ((total_cels // limit)+ 1)  
    
    return render_template('/celulares/celulares_cli.html', cels=cels, pages=pages)

@celulares_views.route("/admin/celulares_list/")
def celulares_list(page=1):
    limit =8
    cels = Celular.get_all(limit=limit, page=page)
    total_cels = Celular.count()
    pages = ((total_cels // limit)+ 1)
    return render_template('/celulares/celulares_list.html', pages=pages, cels=cels)


@celulares_views.route('/celulares/<int:id>/celular/')
def celular(id):
    celular = Celular.get(id)
    if celular is None: abort(404)
    return render_template('celulares/celular.html', celular=celular)

@celulares_views.route('/celulares/<int:id>/celular_cli/')
def celular_cli(id):
    celular = Celular.get(id)
    if celular is None: abort(404)
    return render_template('celulares/celular_cli.html', celular=celular)



@celulares_views.route("/celulares/insertarcelular/", methods=['GET', 'POST'])
def insert_celular():
    form = CreateCelularForm()

    if form.validate_on_submit():
        marca = form.marca.data
        modelo = form.modelo.data
        color = form.color.data 
        stock = form.stock.data
        almacenamiento = form.almacenamiento.data
        condicion = form.condicion.data
        idProveedor = form.idProveedor.data
        precio = form.precio.data
        f = form.image.data
        image = ""
        if f:
            image = save_image(f, 'images/Celulares')
        celular = Celular(marca=marca,
                            modelo=modelo,
                            color=color,
                            stock=stock,
                            almacenamiento=almacenamiento,
                            condicion=condicion,
                            idProveedor=idProveedor,
                            precio=precio,
                            image=image)
        celular.save()
      

        return redirect(url_for('celulares.celulares_list'))

    return render_template('celulares/insertar_cel.html', form=form)

@celulares_views.route('/celulares/<int:id>/updatecel', methods=('GET', 'POST'))
def updatecel(id):
    form = UpdateCelularForm()
    cel = Celular.get(id)
    if cel is None:
        abort(404)
    if form.validate_on_submit():
        cel.modelo=form.marca.data
        cel.color=form.modelo.data
        cel.stock=form.stock.data
        cel.almacenamiento=form.almacenamiento.data
        cel.condicion=form.condicion.data
        cel.idProveedor=form.idProveedor.data
        cel.precio=form.precio.data
        f = form.image.data
        if f:
            image = save_image(f, 'images/Celulares')
            cel.image = image
        cel.save()
        return redirect(url_for('celulares.celulares_list'))
    form.marca.data = cel.marca
    form.modelo.data = cel.modelo
    form.color.data = cel.color
    form.stock.data = cel.stock
    form.almacenamiento.data = cel.almacenamiento
    form.condicion.data = cel.condicion
    form.idProveedor.data = cel.idProveedor
    form.precio.data = cel.precio
    image = cel.image
    return render_template('celulares/insertar_cel.html', form=form, image=image)

@celulares_views.route('/celulares/<int:id>/deletecel/', methods=['POST'])
def deletecel(id):
    Celular.delete_celular(id)

    return redirect(url_for('celulares.celulares_list'))

app/templates/celulares/celular.html
{% extends 'index.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/articulos.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/articulo.css') }}">
{% endblock %}

{% block body %}

<div class="tarjeta">
    <div class="articulo">{{ celular.marca }} </div>
    <div class="articulo">{{ celular.modelo }}</div>
    <div class="articulo">{{ celular.color }}</div>
    <div class="articulo">{{ celular.stock }}</div>
    <div class="articulo">{{ celular.almacenamiento }}</div>
    <div class="articulo">{{ celular.precio }}</div>
    <img src="{{ url_for('static', filename='images/Celulares/' + celular.image) }}" alt="" width="300px">
    </form>
    <p>hola</p>
    

</div>
{% endblock %}

app/templates/celulares/celular_cli.html
{% extends 'index_cliente.html' %}

{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/articulos.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/articulo.css') }}">
{% endblock %}

{% block body %}

<div class="tarjeta">
    <div class="articulo">{{ celular.marca }} </div>
    <div class="articulo">{{ celular.modelo }}</div>
    <div class="articulo">{{ celular.color }}</div>
    <div class="articulo">{{ celular.stock }}</div>
    <div class="articulo">{{ celular.almacenamiento }}</div>
    <div class="articulo">{{ celular.precio }}</div>
    <img src="{{ url_for('static', filename='images/Celulares/' + celular.image) }}" alt="" width="300px">
    <p>hola</p>
    

</div>
{% endblock %}

app/templates/celulares/celulares.html
{% extends 'index.html' %} 
 
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/produtcos.css') }}">
{% endblock %}

{% block  body %}
<div id="titulo"><h1 id="titulo_art">CELULARES</h1></div>    

<section class="seccion">
    {% for cel in cels %}
    <a href="{{ url_for('celulares.celular', id=cel.id) }}">
    <div class="card"> 
    <img src="{{ url_for('static', filename='images/Celulares/' + cel.image) }}" alt="" width="300px" class="img_articulo">
    <div class="item">{{ cel.id }} </div>
    <div class="item">{{ cel.marca }} </div>
    <div class="item">{{ cel.modelo }}</div>
    <div class="item"> {{ cel.color }} </div>
    <div class="item"> {{ cel.stock }} </div>
    <div class="item">{{ cel.almacenamiento }} </div>
    <div class="item"> {{ cel.idProveedor }} </div>
    <div class="item"> {{ cel.precio }} </div>
    </div>
</a>
    {% endfor %}
    
</section>
<div class="paginador">
{% for i in range(pages) %}
<a href="{{ url_for('celulares.celulares', page=(i + 1)) }}" class="paginas" >{{ i + 1 }}</a>
{% endfor %}
</div>



{% endblock %}

app/templates/celulares/celulares_cli.html
{% extends 'index_cliente.html' %} 
 
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/produtcos.css') }}">
{% endblock %}

{% block  body %}
<div id="titulo"><h1 id="titulo_art">CELULARES</h1></div>    

<section class="seccion">
    {% for cel in cels %}
    <a href="{{ url_for('celulares.celular_cli',  id=cel.id) }}">
    <div class="card"> 
    <img src="{{ url_for('static', filename='images/Celulares/' + cel.image) }}" alt="" width="300px" class="img_articulo">

    <div class="item">{{ cel.marca }} </div>
    <div class="item">{{ cel.modelo }}</div>
    <div class="item"> {{ cel.color }} </div>
    <div class="item"> {{ cel.stock }} </div>
    <div class="item">{{ cel.almacenamiento }} </div>
    <div class="item"> {{ cel.idProveedor }} </div>
    <div class="item"> {{ cel.precio }} </div>
    </div>
    </a>
    {% endfor %}
   
</section>
<div class="paginador">
{% for i in range(pages) %}
<a href="{{ url_for('celulares.celulares_cli', page=(i + 1)) }}" class="paginas" >{{ i + 1 }}</a>
</div>
{% endfor %}



{% endblock %}

app/templates/celulares/celulares_list.html
{% extends 'index_admin.html' %} 
 
{% block title %}
    Celulares
{% endblock %}



{% block  body %}
<div id="titulo"><h1 id="titulo_art">LISTA DE CELULARES</h1></div> 
<div class="head">
    <a href="{{ url_for('celulares.insert_celular') }}" class="btn">Agregar celular</a>
</div>

<table id="categories">
    <thead>
        <tr>
            <th>Marca</th>
            <th>Modelo</th>
            <th>Color</th>
            <th>Stock</th>
            <th>Precio</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for cel in cels %}
            <tr>
                <td><a href="{{ url_for('celulares.celular', id=cel.id) }}">{{ cel.marca }}</a></td>
                <td>{{ cel.modelo }}</td>
                <td>{{ cel.color }}</td>
                <td>{{ cel.stock }}</td>
                <td>{{ cel.precio }}</td>
                <td>
                    <a href="{{ url_for('celulares.updatecel', id=cel.id) }}">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-edit" width="36" height="36" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M7 7h-1a2 2 0 0 0 -2 2v9a2 2 0 0 0 2 2h9a2 2 0 0 0 2 -2v-1" />
                        <path d="M20.385 6.585a2.1 2.1 0 0 0 -2.97 -2.97l-8.415 8.385v3h3l8.385 -8.415z" />
                        <path d="M16 5l3 3" />
                      </svg>
                    </a>
                    <form 
                        action="{{ url_for('celulares.deletecel', id=cel.id) }}" 
                        method="post">
                        <button type="submit" onclick="return confirm('Seguro?')">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-trash" width="36" height="36" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                                <path d="M4 7l16 0" />
                                <path d="M10 11l0 6" />
                                <path d="M14 11l0 6" />
                                <path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12" />
                                <path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3" />
                              </svg>
                        </button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<div class="paginador">
{% for i in range(pages) %}
    
<a href="{{ url_for('celulares.celulares_list', page=(i + 1)) }}" class="paginas" >{{ i + 1 }}</a>
    
{% endfor %}
</div>
{% endblock %}

app/templates/celulares/insertar_cel.html
{% extends 'index_admin.html' %}

{% block title %}
Celulares
{% endblock %}
{% block head %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/produtcos.css') }}">

<link rel="stylesheet" href="{{ url_for('static', filename='css/articulo.css') }}">
{% endblock %}

{% block body %}
<h1>Crea </h1>
<form method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    <div>
        {{ form.marca.label }}
        {{ form.marca() }}
    </div>
    <div>
        {{ form.modelo.label }}
        {{ form.modelo() }}
    </div>
    <div>
        {{ form.color.label }}
        {{ form.color() }}
    </div>

   
    <div>
        {{ form.stock.label }}
        {{ form.stock() }}
    </div>
    <div>
        {{ form.almacenamiento.label }}
        {{ form.almacenamiento() }}
    </div>
    <div>
        {{ form.condicion.label }}
        {{ form.condicion() }}
    </div>
    <div>
        {{ form.idProveedor.label }}
        {{ form.idProveedor() }}
    </div>
    <div>
        {{ form.precio.label }}
        {{ form.precio() }}
    </div>
    {% if image %}
    <div>
        <img src="{{ url_for('static', filename='images/Celulares/' + image) }}" alt="" width="200px">
    </div>
    {% endif %}
    <div>
        {{ form.image.label }}
        {{ form.image() }}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>
{% endblock %}