app/views/articulos_views.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash
import traceback

articulos_views = Blueprint('articulos',__name__)

from models.accesorios import Accesorio
from models.audio import Audio
from forms.accesorios_form import CreateAccesorioForm, FiltroBusqueda, UpdateAccesorioForm
from forms.audio_form import CreateAudioForm, UpdateAudioForm

from utils.file_handler import save_image
@articulos_views.route("/articulos")
def articulos():
    accs = Accesorio.get_all_art()
    
    auds = Audio.get_all()
    return render_template('articulos/articulos.html',accs=accs, auds = auds)

@articulos_views.route("/articulos/cli")
def articulos_cli():
    accs = Accesorio.get_all_art()
    
    auds = Audio.get_all()
    return render_template('articulos/articulos_cli.html',accs=accs, auds = auds)

@articulos_views.route("/accesorios/<int:page>")
def accesorios(page=1):
    limit = 8

    accs = Accesorio.get_all(limit=limit, page=page)
    total_acc = Accesorio.count()
    pages = ((total_acc // limit)+ 1)
   
    
    return render_template('articulos/accesorios.html',accs=accs, pages=pages)

@articulos_views.route("/accesorios/cli/<int:page>")
def accesorios_cli(page=1):
    limit = 8
    accs = Accesorio.get_all(limit=limit, page=page)
    total_acc = Accesorio.count()
    pages = ((total_acc // limit)+ 1)
   
    
    return render_template('articulos/accesorios_cli.html',accs=accs, pages=pages)

@articulos_views.route("/admin/listaaccesorios/<int:page>")
def accesorios_list(page=1):
    limit = 8
    accs = Accesorio.get_all(limit=limit, page=page)
    total_acc=Accesorio.count()
    pages = ((total_acc // limit)+ 1)
    return render_template('articulos/accesorios_list.html',accs=accs, pages=pages)

@articulos_views.route("/audios/<int:page>")
def audios(page=1):
    limit = 8
    auds = Audio.get_all(limit=limit, page=page)
    total_aud=Audio.count()
    pages = ((total_aud // limit)+ 1)
    return render_template('articulos/audios.html',auds=auds, pages=pages)

@articulos_views.route("/audios/cli/<int:page>")
def audios_cli(page=1):
    limit = 8
    auds = Audio.get_all(limit=limit, page=page)
    total_aud=Audio.count()
    pages = ((total_aud // limit)+ 1)
    return render_template('articulos/audios_cli.html',auds=auds, pages=pages)

@articulos_views.route("/admin/audios/<int:page>")
def audios_list(page=1):
    limit = 8
    auds = Audio.get_all(limit=limit, page=page)
    total_aud=Audio.count()
    pages = ((total_aud // limit)+ 1)
    return render_template('articulos/audios_list.html',auds=auds, pages=pages)

@articulos_views.route("/articulos/crear_accesorio",  methods=['GET', 'POST'])
def crear_accesorio():
    form = CreateAccesorioForm()
    
    if form.validate_on_submit():
        categoria = form.categoria.data
        tipo = form.tipo.data
        stock = form.stock.data
        color = form.color.data
        especificacionExtra = form.especificacionExtra.data
        precio = form.precio.data
        f = form.image.data
        image = ""
        if f:
            image = save_image(f, 'images/Accesorios')
        accesorio = Accesorio(categoria=categoria, 
                          tipo=tipo,
                          stock=stock,
                          color=color,
                          especificacionExtra=especificacionExtra,
                          precio=precio,
                          image=image)
        accesorio.save()
        flash ('Listo!')
        return redirect(url_for('articulos.accesorios_list', page=1))

    return render_template('articulos/insertar_acc.html', form=form)

@articulos_views.route("/articulos/crear_audio",  methods=['GET', 'POST'])
def crear_audio():
    form = CreateAudioForm()
    
    if form.validate_on_submit():
        marca = form.marca.data
        modelo = form.modelo.data
        conexion = form.conexion.data
        tipo = form.tipo.data
        stock = form.stock.data
        precio = form.precio.data
        f = form.image.data
        image = ""
        if f:
            image = save_image(f, 'images/Audio_img')
        audio = Audio(marca=marca, 
                          modelo=modelo,
                          conexion=conexion,
                          tipo=tipo,
                          stock=stock,
                          precio=precio,
                          image=image)
        audio.save()
        flash ('Listo!')
        return redirect(url_for('articulos.audios_list', page=1))

    return render_template('articulos/insertar_audio.html', form=form)

@articulos_views.route('/articulos/<int:id>/accesorio/')
def accesorio(id):
    accesorio = Accesorio.get(id)
    if accesorio is None: abort(404)
    return render_template('articulos/accesorio.html', accesorio=accesorio)

@articulos_views.route('/articulos/<int:id>/accesorio/cli')
def accesorio_cli(id):
    accesorio = Accesorio.get(id)
    if accesorio is None: abort(404)
    return render_template('articulos/accesorio_cli.html', accesorio=accesorio)




@articulos_views.route('/articulos/<int:id>/audio/')
def audio(id):
    audio = Audio.get(id)
    if audio is None: abort(404)
    return render_template('articulos/audio.html', audio=audio)

@articulos_views.route('/articulos/<int:id>/audio/cli')
def audio_cli(id):
    audio = Audio.get(id)
    if audio is None: abort(404)
    return render_template('articulos/audio_cli.html', audio=audio)

@articulos_views.route('/product/<int:id>/delete_acc/', methods=['POST'])
def delete_acc(id):
    accesorio = Accesorio.get(id)
    if accesorio is None: abort(404)
    accesorio.delete()
    return redirect(url_for('articulos.accesorios_list',page=1))

@articulos_views.route('/product/<int:id>/delete_aud/', methods=['POST'])
def delete_aud(id):
    audio = Audio.get(id)
    if audio is None: abort(404)
    audio.delete()
    return redirect(url_for('articulos.audios_list', page=1))

@articulos_views.route('/products/<int:id>/update_acc/', methods=('GET', 'POST'))
def update_acc(id):
    form = UpdateAccesorioForm()
    accesorio = Accesorio.get(id)
    if accesorio is None:
        abort(404)
    if form.validate_on_submit():
        accesorio.categoria = form.categoria.data
        accesorio.tipo = form.tipo.data
        accesorio.stock = form.stock.data
        accesorio.color = form.color.data
        accesorio.precio = form.precio.data
        accesorio.especificacionExtra = form.especificacionExtra.data
        f = form.image.data
        if f:
            image = save_image(f, 'images/Accesorios')
            accesorio.image = image
        accesorio.save()
        return redirect(url_for('articulos.accesorios_list', page=1))
    form.categoria.data = accesorio.categoria
    form.tipo.data = accesorio.tipo
    form.stock.data = accesorio.stock
    form.color.data = accesorio.color
    form.precio.data = accesorio.precio
    form.especificacionExtra.data = accesorio.especificacionExtra
    image = accesorio.image
    return render_template('articulos/insertar_acc.html', form=form, image=image)

@articulos_views.route('/products/<int:id>/update_audio/', methods=('GET', 'POST'))
def update_audio(id):
    form = UpdateAudioForm()
    audio = Audio.get(id)
    if audio is None:
        abort(404)
    if form.validate_on_submit():
        audio.marca = form.marca.data
        audio.modelo = form.modelo.data
        audio.tipo = form.tipo.data
        audio.conexion = form.conexion.data
        audio.stock = form.stock.data
        audio.precio = form.precio.data
   
        f = form.image.data
        if f:
            image = save_image(f, 'images/Audio_img')
            audio.image = image
        audio.save()
        return redirect(url_for('articulos.audios_list', page=1))
    form.marca.data = audio.marca
    form.modelo.data= audio.modelo
    form.tipo.data = audio.tipo
    form.conexion.data = audio.conexion
    form.stock.data = audio.stock
    form.precio.data = audio.precio
    image = audio.image
   
    
    return render_template('articulos/insertar_audio.html', form=form, image=image)

app/views/celulares_views.py
from flask import Blueprint, render_template, redirect, url_for, abort
from models.celulares import Celular
import traceback

from forms.celulares_form import CreateCelularForm, UpdateCelularForm

from utils.file_handler import save_image

celulares_views = Blueprint('celulares',__name__)

@celulares_views.route("/celulares/<int:page>")
def celulares(page=1):
    limit = 8

    cels = Celular.get_all(limit=limit, page=page)
    total_cels = Celular.count()
    pages = ((total_cels // limit)+ 1)
    return render_template('/celulares/celulares.html', pages=pages, cels=cels)

@celulares_views.route("/celulares_cli/<int:page>")
def celulares_cli(page=1):
    limit = 8

    cels = Celular.get_all(limit=limit, page=page)
    total_cels = Celular.count()
    pages = ((total_cels // limit)+ 1)  
    
    return render_template('/celulares/celulares_cli.html', cels=cels, pages=pages)

@celulares_views.route("/admin/celulares_list/")
def celulares_list(page=1):
    limit =8
    cels = Celular.get_all(limit=limit, page=page)
    total_cels = Celular.count()
    pages = ((total_cels // limit)+ 1)
    return render_template('/celulares/celulares_list.html', pages=pages, cels=cels)


@celulares_views.route('/celulares/<int:id>/celular/')
def celular(id):
    celular = Celular.get(id)
    if celular is None: abort(404)
    return render_template('celulares/celular.html', celular=celular)

@celulares_views.route('/celulares/<int:id>/celular_cli/')
def celular_cli(id):
    celular = Celular.get(id)
    if celular is None: abort(404)
    return render_template('celulares/celular_cli.html', celular=celular)



@celulares_views.route("/celulares/insertarcelular/", methods=['GET', 'POST'])
def insert_celular():
    form = CreateCelularForm()

    if form.validate_on_submit():
        marca = form.marca.data
        modelo = form.modelo.data
        color = form.color.data 
        stock = form.stock.data
        almacenamiento = form.almacenamiento.data
        condicion = form.condicion.data
        idProveedor = form.idProveedor.data
        precio = form.precio.data
        f = form.image.data
        image = ""
        if f:
            image = save_image(f, 'images/Celulares')
        celular = Celular(marca=marca,
                            modelo=modelo,
                            color=color,
                            stock=stock,
                            almacenamiento=almacenamiento,
                            condicion=condicion,
                            idProveedor=idProveedor,
                            precio=precio,
                            image=image)
        celular.save()
      

        return redirect(url_for('celulares.celulares_list'))

    return render_template('celulares/insertar_cel.html', form=form)

@celulares_views.route('/celulares/<int:id>/updatecel', methods=('GET', 'POST'))
def updatecel(id):
    form = UpdateCelularForm()
    cel = Celular.get(id)
    if cel is None:
        abort(404)
    if form.validate_on_submit():
        cel.modelo=form.marca.data
        cel.color=form.modelo.data
        cel.stock=form.stock.data
        cel.almacenamiento=form.almacenamiento.data
        cel.condicion=form.condicion.data
        cel.idProveedor=form.idProveedor.data
        cel.precio=form.precio.data
        f = form.image.data
        if f:
            image = save_image(f, 'images/Celulares')
            cel.image = image
        cel.save()
        return redirect(url_for('celulares.celulares_list'))
    form.marca.data = cel.marca
    form.modelo.data = cel.modelo
    form.color.data = cel.color
    form.stock.data = cel.stock
    form.almacenamiento.data = cel.almacenamiento
    form.condicion.data = cel.condicion
    form.idProveedor.data = cel.idProveedor
    form.precio.data = cel.precio
    image = cel.image
    return render_template('celulares/insertar_cel.html', form=form, image=image)

@celulares_views.route('/celulares/<int:id>/deletecel/', methods=['POST'])
def deletecel(id):
    Celular.delete_celular(id)

    return redirect(url_for('celulares.celulares_list'))

app/views/home_views.py
from flask import Blueprint, render_template

home_views = Blueprint('home',__name__)

@home_views.route("/")
def home_user():
      
    return render_template('home/home_user.html')

@home_views.route("/cliente")
def home_cliente():
    return render_template('home/home_cliente.html')

@home_views.route("/admin")
def home_admin():
    return render_template("home/home_admin.html")

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flaskapp</title>
 
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    {% block head %}
    
     {% endblock %}
  </head>
<body>
    <nav>
       
        <ul class="navegador">
           <a href="{{ url_for('home.home_user') }}"><img src="{{ url_for('static', filename='images/logo_softcel.png') }}" alt="imagen_nav" id="imagen_nav"></a>
           <li><span>Soporte</span></li>
           <li><span>Reparaciones</span></li>
            <li><a href="{{ url_for('articulos.articulos') }}">Articulos</a></li>
            <li><a href="{{ url_for('celulares.celulares', page=1) }}">Celulares</a></li>
            
            <li><a href="{{ url_for('login') }}">Login</a></li>
        </ul>
    </nav>
    <section class="contenido">
      
      {% block body %}
      
      {% endblock %}
      
    </section>

    <footer>
      <h2>footer</h2>
          </footer>
</body>
</html>

app/templates/index_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flaskapp</title>
 
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    {% block head %}
    
     {% endblock %}
  </head>
<body>
    <nav>
       
        <ul class="navegador" id="nav_admin">
           <a href="{{ url_for('home.home_admin') }}"><img src="{{ url_for('static', filename='images/logo_softcel.png') }}" alt="imagen_nav" id="imagen_nav"></a>
            <li><a href="{{ url_for('articulos.accesorios_list', page=1) }}">Accesorios</a></li>
            <li><a href="{{ url_for('articulos.audios_list', page=1) }}">Audios</a></li>
            <li><a href="{{ url_for('celulares.celulares_list', page=1) }}">Celulares</a></li>
            <li><a href="{{ url_for('Reparacion.citas_list') }}">Citas</a></li>
            <li><a href="{{ url_for('Reparacion.reparacion_list') }}">Reparaciones</a></li>
            <li><a href="{{ url_for('soporte.soporte_list') }}">Quejas</a></li>
            
            <li><a href="{{ url_for('logout') }}">Cerrar sesion</a></li>
        </ul>
    </nav>
    <section class="contenido">
      
      {% block body %}
      
      {% endblock %}
      
    </section>

    
</body>
</html>

app/templates/index_cliente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flaskapp</title>
 
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    {% block head %}
    
     {% endblock %}
  </head>
<body>
    <nav>
       
        <ul class="navegador">
           <a href="{{ url_for('home.home_cliente') }}"><img src="{{ url_for('static', filename='images/logo_softcel.png') }}" alt="imagen_nav" id="imagen_nav"></a>
            <li><a href="{{ url_for('soporte.soporte') }}">Soporte</a></li>
            <li><a href="{{ url_for('Reparacion.reparacion', page=1) }}">Reparaciones</a></li>
            <li><a href="{{ url_for('articulos.articulos_cli', page=1) }}">Articulos</a></li>
            <li><a href="{{ url_for('celulares.celulares_cli', page=1) }}">Celulares</a></li>
            
            <li><a href="{{ url_for('logout') }}">Cerrar sesion</a></li>
        </ul>
    </nav>
    <section class="contenido">
      
      {% block body %}
      
      {% endblock %}
      
    </section>

    <footer>
      <h2>footer</h2>
          </footer>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/stylelogin.css') }}">
</head>
<body>
    <h1>Login</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="alert alert-success">
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    <form method="post">
        <label for="correo">Correo:</label>
        <input type="email" name="correo" required>
        <br>
        <label for="password">Contraseña:</label>
        <input type="password" name="password" required>
        <br>
        <input type="submit" value="Iniciar sesión">
    </form>
    <a href="{{ url_for('registro') }}">Registrarse</a>
</body>
</html>

app/templates/registro.html
<!DOCTYPE html>
<html>
<head>
    <title>Registro</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/stylelogin.css') }}">
</head>
<body>
    <h1>Registro</h1>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul class="alert alert-error">
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endwith %}
    <form method="post">
        <label for="nombre">Nombre:</label>
        <input type="text" name="nombre" required>
        <br>
        <label for="correo">Correo:</label>
        <input type="email" name="correo" required>
        <br>
        <label for="password">Contraseña:</label>
        <input type="password" name="password" required>
        <br>
        <input type="submit" value="Registrarse">
    </form>
    <a href="{{ url_for('login') }}">Volver al login</a>
</body>
</html>